spring:
  datasource:
    url: jdbc:h2:mem:k
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        security=DEBUG:

# need to remove values when realize
server:
  jwt:
    token:
      signing:
        key: aef72d8bc84e66100cbaba56bf48d91e197f342b0f6cd96b5575f9fbc9ccb629