spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task_management_system}
    username: ${DB_USER:task_management_system}
    password: ${DB_PASSWORD:task_management_system}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  jwt:
    token:
      signing:
        key: ${JWT_SIGNING_KEY:aef72d8bc84e66100cbaba56bf48d91e197f342b0f6cd96b5575f9fbc9ccb629}